name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pushd ..
        git clone --depth 1 https://github.com/fastily/pwiki.git
        pip install -e pwiki
        popd
        pip install -r requirements-dev.txt
    - name: Test
      run: |
        python -m unittest